// Generated by CoffeeScript 1.6.3
(function() {
  var Board, Canvas, Food, Game, Point, Snake, SnakeSegment, backgroundColor, foodColor, headColor, height, snakeColor, width,
    __hasProp = {}.hasOwnProperty;

  width = 60;

  height = 40;

  backgroundColor = 'white';

  headColor = 'red';

  snakeColor = 'green';

  foodColor = 'orange';

  Board = (function() {
    function Board() {
      var row, _, _i, _j;
      this.array = [];
      for (_ = _i = 0; 0 <= height ? _i < height : _i > height; _ = 0 <= height ? ++_i : --_i) {
        row = [];
        for (_ = _j = 0; 0 <= width ? _j < width : _j > width; _ = 0 <= width ? ++_j : --_j) {
          row.push(0);
        }
        this.array.push(row);
      }
    }

    Board.prototype.clear = function() {
      var x, y, _i, _results;
      _results = [];
      for (y = _i = 0; 0 <= height ? _i < height : _i > height; y = 0 <= height ? ++_i : --_i) {
        _results.push((function() {
          var _j, _results1;
          _results1 = [];
          for (x = _j = 0; 0 <= width ? _j < width : _j > width; x = 0 <= width ? ++_j : --_j) {
            _results1.push(this.set(x, y, 0));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Board.prototype.get = function(x, y) {
      return this.array[y][x];
    };

    Board.prototype.set = function(x, y, value) {
      return this.array[y][x] = value;
    };

    return Board;

  })();

  Canvas = (function() {
    Canvas.prototype.width = width * 10;

    Canvas.prototype.height = height * 10;

    function Canvas() {
      this.canvas = document.getElementById('myCanvas');
      this.ctx = this.canvas.getContext('2d');
    }

    Canvas.prototype.paint = function(board) {
      var x, y, _i, _results;
      _results = [];
      for (y = _i = 0; 0 <= height ? _i < height : _i > height; y = 0 <= height ? ++_i : --_i) {
        _results.push((function() {
          var _j, _results1;
          _results1 = [];
          for (x = _j = 0; 0 <= width ? _j < width : _j > width; x = 0 <= width ? ++_j : --_j) {
            switch (board.get(x, y)) {
              case 1:
                this.ctx.fillStyle = snakeColor;
                break;
              case 2:
                this.ctx.fillStyle = headColor;
                break;
              case 3:
                this.ctx.fillStyle = foodColor;
                break;
              default:
                this.ctx.fillStyle = backgroundColor;
            }
            _results1.push(this.ctx.fillRect(x * 10, y * 10, 10, 10));
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    return Canvas;

  })();

  Point = (function() {
    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    return Point;

  })();

  Food = (function() {
    function Food(x, y, value) {
      this.x = x;
      this.y = y;
      this.value = value != null ? value : 3;
    }

    Food.prototype.project = function(board) {
      board.set(this.x, this.y, 3);
      return console.log('food at', this.x, this.y);
    };

    return Food;

  })();

  SnakeSegment = (function() {
    function SnakeSegment(x, y, next) {
      this.x = x;
      this.y = y;
      this.next = next != null ? next : null;
    }

    return SnakeSegment;

  })();

  Snake = (function() {
    function Snake(direction) {
      var middle, tail;
      this.direction = direction != null ? direction : 'down';
      tail = new SnakeSegment(10, 12);
      middle = new SnakeSegment(10, 11, tail);
      this.head = new SnakeSegment(10, 10, middle);
    }

    Snake.prototype.move = function() {
      var newHead, segment, _results;
      newHead = (function() {
        switch (this.direction) {
          case 'left':
            return new SnakeSegment(this.head.x - 1, this.head.y, this.head);
          case 'right':
            return new SnakeSegment(this.head.x + 1, this.head.y, this.head);
          case 'up':
            return new SnakeSegment(this.head.x, this.head.y - 1, this.head);
          case 'down':
            return new SnakeSegment(this.head.x, this.head.y + 1, this.head);
        }
      }).call(this);
      this.head = newHead;
      if (this.extra > 0) {
        this.extra--;
        return;
      }
      segment = this.head;
      _results = [];
      while (segment) {
        if (segment.next && !segment.next.next) {
          segment.next = null;
          break;
        }
        _results.push(segment = segment.next);
      }
      return _results;
    };

    Snake.prototype.project = function(board) {
      var segment, _results;
      board.set(this.head.x, this.head.y, 2);
      segment = this.head.next;
      _results = [];
      while (segment) {
        board.set(segment.x, segment.y, 1);
        _results.push(segment = segment.next);
      }
      return _results;
    };

    Snake.prototype.checkPointIsOccupied = function(point) {
      var segment;
      segment = this.head.next;
      while (segment) {
        if (segment.x === point.x && segment.y === point.y) {
          return true;
        }
        if (point.x > 59 || point.x < 0 || point.y < 0 || point.y > 39) {
          return true;
        }
        segment = segment.next;
      }
      return false;
    };

    Snake.prototype.countNeighbours = function(point) {
      var result;
      result = 0;
      if (this.checkPointIsOccupied(new Point(point.x, point.y + 1))) {
        result++;
      }
      if (this.checkPointIsOccupied(new Point(point.x, point.y - 1))) {
        result++;
      }
      if (this.checkPointIsOccupied(new Point(point.x + 1, point.y))) {
        result++;
      }
      if (this.checkPointIsOccupied(new Point(point.x - 1, point.y))) {
        result++;
      }
      return result;
    };

    return Snake;

  })();

  Game = (function() {
    function Game() {
      var processCallback;
      this.canvas = new Canvas;
      this.board = new Board;
      this.snake = new Snake;
      this.snake.project(this.board);
      this.food = this.addFood(this.board);
      this.food.project(this.board);
      this.canvas.paint(this.board);
      processCallback = this.process.bind(this);
      this.processing = setInterval(processCallback, 30);
    }

    Game.prototype.randomInt = function(lower, upper) {
      var start;
      start = Math.random();
      return Math.floor(start * (upper - lower + 1) + lower);
    };

    Game.prototype.addFood = function(board) {
      var x, y;
      while (true) {
        x = this.randomInt(0, width - 1);
        y = this.randomInt(0, height - 1);
        if (board.get(x, y) === 0) {
          break;
        }
      }
      return new Food(x, y, 3);
    };

    Game.prototype.gameOver = function() {
      clearInterval(this.processing);
      return document.getElementsByTagName('body')[0].className += ' tragedy';
    };

    Game.prototype.process = function() {
      this.snake.move();
      this.board.clear();
      this.snake.project(this.board);
      this.food.project(this.board);
      return this.canvas.paint(this.board);
    };

    Game.prototype.checkFourPointsAround = function(point) {};

    Game.prototype.checkForClosedSpace = function(direction) {};

    Game.prototype.think = function() {
      var directions, distance, distances, key, neighbours, value, x, y;
      x = this.snake.head.x;
      y = this.snake.head.y;
      directions = {
        up: new Point(x, y - 1),
        down: new Point(x, y + 1),
        left: new Point(x - 1, y),
        right: new Point(x + 1, y)
      };
      for (key in directions) {
        if (!__hasProp.call(directions, key)) continue;
        value = directions[key];
        if (this.snake.checkPointIsOccupied(value)) {
          delete directions[key];
        }
      }
      for (key in directions) {
        if (!__hasProp.call(directions, key)) continue;
        value = directions[key];
        if (this.checkForClosedSpace(value)) {
          delete directions[key];
        }
      }
      distances = [];
      for (key in directions) {
        if (!__hasProp.call(directions, key)) continue;
        value = directions[key];
        distance = this.food.distance(value);
        neighbours = this.snake.countNeighbours(value);
        if (neighbours < 3) {
          distances.push([key, distance]);
        }
      }
      distances.sort(function(a, b) {
        return a[1] - b[1];
      });
      if (distances.length > 0) {
        return this.snake.direction = distances[0][0];
      }
    };

    return Game;

  })();

  window.start = function() {
    var game;
    return game = new Game;
  };

}).call(this);

/*
//@ sourceMappingURL=code.map
*/
